name: CI

on:
  push:
    branches-ignore:
      - 'master'
      - 'ci/**'
      - '!ci/gha**'
  pull_request:
    branches:
      - 'master'

jobs:
  icc:
    runs-on: ubuntu-22.04
    env:
      CC: /home/runner/.local/bin/icx
      CXX: /home/runner/.local/bin/icpx
      CFLAGS: -Wall -Werror -march=native -Wno-tautological-constant-compare
      CXXFLAGS: -Wall -Werror -march=native -Wno-tautological-constant-compare
    steps:
    - uses: actions/checkout@v2
    - name: CPU Information
      run: cat /proc/cpuinfo
    - name: Install APT Dependencies
      run: sudo apt-get install -y ninja-build ninja-build python3-pip && sudo pip install meson==0.64
    - name: Install ICC
      run: |
        # download the key to system keyring
        wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
        | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
        # add signed entry to apt sources and configure the APT client to use Intel repository:
        echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update
        sudo apt-get install -y intel-oneapi-compiler-dpcpp-cpp
        mkdir -p ~/.local/bin/ || true
        for exe in icx icpx; do
          printf '#!/bin/bash\nARGS="$@"\nsource /opt/intel/oneapi/compiler/latest/env/vars.sh >/dev/null\n%s ${ARGS}\n' "${exe}" > ~/.local/bin/"${exe}"
          chmod 0755 ~/.local/bin/"${exe}";
        done
    - name: Configure
      run: meson setup build
    - name: Build
      run: ninja -C build -v
    - name: Test
      run: ninja -C build -v test
