name: CI

on:
  push:
    branches-ignore:
      - 'master'
      - 'ci/**'
      - '!ci/gha**'
  pull_request:
    branches:
      - 'master'

jobs:
  x86-sde:
    runs-on: ubuntu-22.04
    env:
      CFLAGS: -Wall -Wextra -Werror -msse2
      CXXFLAGS: -Wall -Wextra -Werror -msse2
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: CPU Information
      run: cat /proc/cpuinfo
    - name: Install APT Dependencies
      run: sudo apt-get update && sudo apt-get install -y ninja-build ninja-build meson parallel gcovr
    - name: Configure
      run: meson setup build -Db_coverage=true
    - name: Build
      run: ninja -C build -v
    - name: Test
      run: meson test -C build --print-errorlogs --wrapper "${GITHUB_WORKSPACE}/test/check-flags.sh sde"
    - name: Echo SDE log
      run: cat /home/runner/work/simde/simde/build/meson-logs/testlog.txt
